### PR TITLE
Feat/ride requests

### PR DESCRIPTION
**Pull request by Erick-Suarez**
## Changes proposed in this pull request
1. Merge rider and driver request pages into one
2. Add UI styling reflective of the mockups
3. set up foundation for popups

@bruinpool-devs

### CODE REVIEW

**Comment by jhan25** [comment]
Also to keep format consistent, make sure you have format on save enabled in your settings, and add the Prettier extension for consistent format (recommend VS code editor)

**Comment by jhan25** [comment]
The push I made labeled "formatted code" is just reformatting of the code you wrote using the Prettier extension + format on save

**Comment by jhan25** [comment]
Also don't forget the pending/declined/accepted part should be replaced with "view profile" for the request feed in the my drives page. Refer to figma for confirmation

**Comment by jhan25** [comment]
Also I'm assuming the PendingRequestModal isn't completed yet? It would be nice if you could complete the modal and have it functioning before we merge this branch to master

**Comment by jhan25** [comment]
Other than that, the changes look good! Really appreciate the help Erick :)

**Comment by Erick-Suarez** [comment]
> The push I made labeled "formatted code" is just reformatting of the code you wrote using the Prettier extension + format on save

I'll get that extension rn!

**Comment by Erick-Suarez** [comment]
> error
> 
> For some reason there's a scroll bar being rendered for the text block containing the date and time. Might wanna just use a div and define explicit height/width (instead of pre tag)

I'll write down a task to get that looked at

**Comment by Erick-Suarez** [comment]
> Also don't forget the pending/declined/accepted part should be replaced with "view profile" for the request feed in the my drives page. Refer to figma for confirmation

Thanks for the reminder, I'll keep that in mind

**Pull request merged**
